---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: ui-centos7
  #   image: quay.io/egi/voms-client:centos7
  - name: ui-almalinux9
    image: quay.io/egi/voms-client:almalinux9
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../
  config_options:
    defaults:
      stdout_callback: yaml

  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  enabled: true
  # Parallel testing only possible with xdist
  options:
    n: 2
