---
name: Lint

on: [push, pull_request]
permissions: read-all
jobs:
  super-lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Runs the Super-Linter action
      # - name: Run Super-Linter on new changes
      #   uses: docker://ghcr.io/github/super-linter:slim-v4
      #   env:
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # Only check new or edited files
      #     VALIDATE_ALL_CODEBASE: false
      #     # Fail on errors
      #     DISABLE_ERRORS: false
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v8.4.2
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
